### PR TITLE
Made it EXTREMELY clear that streisand is (usually) meant to be run on a local machine

### PR DESCRIPTION
**Pull request by peterpacz1**
Many of the bugs in the bug tracker are usually misunderstandings about how streisand's provsioning system works. Streisand is based on [Ansible](http://www.ansible.com/home) - which provisions and spins up a NEW server.

Many new users do not understand this, and end up running streisand on their remote machine. In this commit, I edit the `README.MD` file to add a clear clarification on top of the installation instruction section to make this clearer. 

The commit is self contained to `README.MD`, and should be easily mergeable. Spellcheck'ed and ready for action.

### CODE REVIEW

**Comment by faddat** [comment]
Seconded x100.

**Comment by soyuka** [comment]
You can also run this on a new server locally by changing some parameters.

**Comment by peterpacz1** [comment]
@soyuka yes, I know - you have to edit the ansible hosts file, I believe.

**Comment by jlund** [comment]
Thank you very much for this contribution. I think that it will help prevent a lot of confusion, and I apologize that I didn't get a chance to look at it until now.

I am planning on making local provisioning (i.e. Streisand/Ansible locally configuring the system on which they are installed) a first-class option soon. I still need to work out some kinks, but I will be sure to let all of you know when I have a branch ready for testing. Until then, this is a great addition to the README.

**Pull request merged**
