### PR TITLE
Update instructions.md.j2

### PR DESCRIPTION
**Pull request by skeeve42**
Updated instructions to add servers using a QR code on both Windows and OS X.

### CODE REVIEW

**Comment by skeeve42** [comment]
So I just tried to install shadowsocks on a different windows machine using the streisand instructions, and I realized the instructions and mirrors are pointed to the old shadowsocks-gui:
https://github.com/shadowsocks/shadowsocks-gui.
The project has now been split, so the links are are outdated...the mirror downloads and old version of shadowsocks that does not support QRcode scanning.

**Comment by skeeve42** [comment]
https://github.com/shadowsocks/shadowsocks
This is the main page for the server which has links to all the client projects.

**Comment by peterpacz1** [comment]
Looks good to me - let's hope Jlund sees this and the other requests.

**Comment by jlund** [comment]
Thanks, @skeeve42! I'm updating the files that get mirrored now.

**Comment by jlund** [comment]
All set!

**Comment by skeeve42** [comment]
Cool!

**Pull request merged**
