### PR TITLE
Configure Wireguard Client On Systemd Linux Distros

### PR DESCRIPTION
**Pull request by HougeLangley**
Adding systemd configure of Wireguard.

Sorry for my English.

### CODE REVIEW

**Comment by HougeLangley** [comment]
Chinese translation not complete.

**Comment by cpu** [comment]
Hi @HougeLangley,

A Chinese translation would be great but it should be a separate pull request. Please only include your first commit, 825cb9b, in this PR and then open a separate one for any other work. It's much easier to keep track of that way!

Thanks!

**Comment by HougeLangley** [comment]
@cpu OK, I have been removed the not complete translation work. If done I will push.

Thank you for your job.

**Comment by HougeLangley** [comment]
@cpu Dude, I have no idea how remove these incorrect commits. could you using 62efb54 ?

**Comment by cpu** [comment]
@HougeLangley No problem! It can be a little bit tricky to rebase :-) After I finish work today I can fix this PR for you and see about merging it. Thanks for sticking with it!

**Comment by HougeLangley** [comment]
@cpu Thank you for your help.

**Comment by cpu** [comment]
@HougeLangley Happy to help! I cherry-picked 825cb9b into a new pull-request: https://github.com/jlund/streisand/pull/860 Doing it that way should preserve that you're the original author and mark your first contribution :tada: I'm going to close this PR now since its been replaced. Thanks again!

**Pull request closed without merging**
