### PR TITLE
README updates

### PR DESCRIPTION
**Pull request by alimakki**
- Update Azure pip instructions from #940
 - Language names written in native language in README-ru to be consistent
 - Added mirror links in README-ru

### CODE REVIEW

**Comment by alimakki** [comment]
@levleontiev, would you be able to go over the README-ru.md and see if 'mirror' was translated correctly?

Would be greatly appreciated!

**Comment by levleontiev** [comment]
"Mirror" is translated correctly.

**Comment by alimakki** [comment]
@levleontiev Thanks!

**Comment by cpu** [comment]
Thanks all!

**Pull request merged**
